name: Create issues for muted tests

on:
  pull_request:
    types:
      - labeled
  pull_request_review:
    types:
      - submitted
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRANCH_FOR_PR: update-muted-ya
  BASE_BRANCH: main
  MUTED_YA_FILE_PATH: .github/scripts/tests/muted_ya.txt

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && contains(github.pull_request.labels.*.name, 'mute-unmute') 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: ${{ env.BRANCH_FOR_PR }}_${{ env.BASE_BRANCH }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install ydb[yc] PyGithub

      - name: Setup ydb access
        uses: ./.github/actions/setup_ci_ydb_service_account_key_file_credentials
        with:
            ci_ydb_service_account_key_file_credentials: ${{ secrets.CI_YDB_SERVICE_ACCOUNT_KEY_FILE_CREDENTIALS }}

      - name: Create issues for muted tests
        id: create_issues
        run: |
            .github/scripts/tests/create_new_muted_ya.py create_issues --file_path=${{ github.workspace }}/${{ env.MUTED_YA_FILE_PATH }} 
    
      - name: Add issues to PR
        env:
            GITHUB_TOKEN: ${{ env.GH_TOKEN }}
        run: |
            python .github/scripts/create_or_update_pr.py append_pr_body --pr_number=${{ github.event.pull_request.number }} --body=${{ steps.create_issues.outputs.created_issues_file }}
        