name: Regression-whitelist-run

on:
  schedule:
    - cron: "0 23 * * *"  # At 23:00 every day
  workflow_dispatch:
env:
  BRANCHES: ${{ github.event_name == 'workflow_dispatch' && github.ref || '["main", "stable-25-1", "stable-25-1-1"]' }}
jobs:
  main:
    name: Whitelist-run
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit

    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(env.BRANCHES) }}
        build_preset: ["relwithdebinfo", "release-asan", "release-tsan", "release-msan"]
    with:
      test_targets: ydb/tests/sql/ ydb/tests/stress ydb/tests/functional/tpc ydb/tests/functional/benchmarks_init
      ref: ${{ matrix.branch }}
      build_preset: ${{ matrix.build_preset }}
