name: Regression-whitelist-run

on:
  schedule:
    - cron: "0 23 * * *"  # At 23:00 every day
  workflow_dispatch:
    inputs:
      branches:
        description: 'Branches to run tests on (comma-separated)'
        default: 'main, stable-25-1, stable-25-1-1'
        required: false

jobs:
  main:
    name: Whitelist-run
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
    env:
      DEFAULT_BRANCHES: 'main, stable-25-1, stable-25-1-1'
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ split(replace(github.event.inputs.branches || env.DEFAULT_BRANCHES, ' ', ''), ',') }}
        build_preset: ["relwithdebinfo", "release-asan", "release-tsan", "release-msan"]
    with:
      test_targets: ydb/tests/sql/ ydb/tests/stress ydb/tests/functional/tpc ydb/tests/functional/benchmarks_init
      ref: ${{ matrix.branch }}
      build_preset: ${{ matrix.build_preset }}
