name: Regression-run_Small_and_Medium

on:
  schedule:
    - cron: "0 23 * * *"  # At 23:00 every day
  workflow_dispatch:

jobs:
  main:
    name: Regression-run_Small_and_Medium
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: 
         build_preset: ["relwithdebinfo", "release-asan", "release-tsan", "release-msan"]
         branch: [main, stable-25-1, stable-25-1-1, stable-25-1-analytics] 
    with:
      test_targets: ydb/
      test_size: small,medium
      build_preset: ${{ matrix.build_preset }}
      ref: ${{  matrix.branch || github.ref_name }}

