name: Regression-run

on:
  schedule:
    - cron: "55 23 * * *"  # At 23:55 every day
  workflow_dispatch:

jobs:
  main:
    name: Regression-run
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: 
        branch: [main, stable-25-1, stable-25-1-1, stable-25-1-analytics] 
        build_preset: ["relwithdebinfo", "release-asan", "release-tsan", "release-msan"]
    with:
      test_targets: ydb/
      ref: ${{ matrix.branch }}
      build_preset: ${{ matrix.build_preset }}