name: Regression-whitelist-run

on:
  schedule:
    - cron: "0 23 * * *"  # At 23:00 every day
  workflow_dispatch:
    inputs:
      branches:
        description: 'Branches to run tests on, it shoud be like ["branch_name1", "branch_name2"]'
        default:  ${{ env.DEFAULT_BRANCHES }}
        required: false

env:
   DEFAULT_BRANCHES: '["main", "stable-25-1", "stable-25-1-1"]'

jobs:
  main:
    name: Whitelist-run
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ github.event_name == 'workflow_dispatch' && fromJson(inputs.branches || env.DEFAULT_BRANCHES) || fromJson(env.DEFAULT_BRANCHES) }}
        build_preset: ["relwithdebinfo", "release-asan", "release-tsan", "release-msan"]
    with:
      test_targets: ydb/tests/sql/ ydb/tests/stress ydb/tests/functional/tpc ydb/tests/functional/benchmarks_init
      ref: ${{ matrix.branch }}
      build_preset: ${{ matrix.build_preset }}