name: Regression-run_Small_and_Medium

on:
  schedule:
    - cron: "30 23 * * *"  # At 23:30 every day
  workflow_dispatch:
    inputs:
      branches:
        description: 'Branches to test (JSON array or single branch name)'
        required: false


env:
  DEFAULT_BRANCHES: '["main", "stable-25-1", "stable-25-1-1"]'

jobs:
  main:
    name: Regression-run_Small_and_Medium
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: 
        build_preset: ["relwithdebinfo", "release-asan", "release-tsan", "release-msan"]
    with:
      test_targets: ydb/
      test_size: small,medium
      branches: ${{ inputs.branches || '["main", "stable-25-1", "stable-25-1-1"]' }}
      build_preset: ${{ matrix.build_preset }}
