name: Regression-run_Large

on:
  schedule:
    - cron: "30 23 * * *"  # At 23:00 every day
  workflow_dispatch:

jobs:
  main:
    name: Regression-run_Large
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix: 
        branch: [main, stable-25-1, stable-25-1-1] 
        build_preset: ["relwithdebinfo", "release-asan", "release-tsan", "release-msan"]
    with:
      test_targets: ydb/
      test_size: large
      ref: ${{  matrix.branch}}
      build_preset: ${{ matrix.build_preset }}
